### ISSUE TITLE
Failed to import analytics-clj.core

### ISSUE THREAD

**Issue by nitinprakash96** [circleci/analytics-clj#11]
Whenever I try to run the repl after importing `analytics-clj.core`, I end up with the message `Call to clojure.core/ns did not conform to a spec`. Looking deeper into the stack trace, I see the following trace:
```clojure
{:type clojure.lang.Compiler$CompilerException
   :message "Syntax error macroexpanding clojure.core/ns at (circleci/analytics_clj/utils.clj:1:1)."
   :data #:clojure.error{:phase :macro-syntax-check, :line 1, :column 1, :source "circleci/analytics_clj/utils.clj", :symbol clojure.core/ns}
   :at [clojure.lang.Compiler checkSpecs "Compiler.java" 6972]}
```

Importing `analytics-clj.external` works just fine.

Dependency: `[circleci/analytics-clj "0.8.0"]`
Clojure version: `1.10.1`
Import statement: `(:require  [circleci.analytics-clj.core :as a])`

Could this be due to a malformed ns in `utils` or because of someother dependeny in my `project.clj`?

**Comment by bostonaholic** [comment]
This was fixed in `0.4.1` via #2. If you're still experiencing problems, could you provide the version of the library you're using.

**Comment by nitinprakash96** [comment]
Oh I see. I was using `0.4.0` as described in https://segment.com/docs/sources/server/clojure/. Upgrading to `0.8.0` solves my problem. Thank you!

**Comment by bostonaholic** [comment]
Glad it worked for you, @nitinprakash96.

@f2prateek what is the process for getting the docs that are hosted by Segment to get updates when they are published to this library?
