### ISSUE TITLE
Update Java lib version to fix events dropped from queue on flush/shutdown  

### ISSUE THREAD

**Issue by cmardirosrvu** [circleci/analytics-clj#16]
Java lib version 2.1.1 has a bug that causes messages in the queue to be dropped when calling `shutdown`. Adding a sleep between `flush` and `shutdown` is needed to avoid dropped messages. This appears to have been fixed with this PR https://github.com/segmentio/analytics-java/pull/192. Can we please bump the version of the Java lib used in this repo

**Comment by stig** [comment]
This should be fixed by the new release published to Clojars today: https://clojars.org/circleci/analytics-clj/versions/0.10.2
