### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by slipset** [circleci/analytics-clj#18]
Sorry for the noise, but any chance of getting a new release?

**Comment by onetom** [comment]
Sounds like this can be closed now, although I see some inconsistencies between the docs recommending version `0.8.0`:
https://segment.com/docs/connections/sources/catalog/libraries/server/clojure/

while the [CHANGELOG.md](https://github.com/circleci/analytics-clj/blob/9f86ca98202babd34462ef2d0c516e8a1ef360b6/CHANGELOG.md) talks about `0.8.1` from *September 1, 2022*

but in IntelliJ I'm offered to upgrade to version `0.9.0`, which is the version seen on https://clojars.org/circleci/analytics-clj
which was pushed BEFORE `0.8.1` release date:

Pushed by
[marcomorain](https://clojars.org/users/marcomorain) on Nov 18, 2021 with [this git tree](https://github.com/circleci/analytics-clj/tree/3bd0456950c0b2b95eb4ce6157985f433cfe723f)

BUT that git version is not even accessible, which smells very fishy!

**Comment by stig** [comment]
I've spent some time learning about publishing to Clojars today, and there's now a [0.10.2 on Clojars](https://clojars.org/circleci/analytics-clj/versions/0.10.2) that was automatically published by [this workflow](https://app.circleci.com/pipelines/github/circleci/analytics-clj/137/workflows/24dbe15b-6ea1-4dc2-bdc2-de5e383dc84a) when I pushed the tag [v0.10.2](https://github.com/circleci/analytics-clj/releases/tag/v0.10.2) tag.
